### ISSUE TITLE
The polyfill is requiring a valid value of background-image

### ISSUE THREAD

**Issue by ianthedev** [preciousforever/SVG-Stacker#9]
Due to [how the polyfill is working](https://github.com/preciousforever/SVG-Stacker/blob/master/fixsvgstack.jquery.js#L104), when we are writing code only for browsers which need to be fixed, the following code is supposed to work, but it doesn't currently:

``` CSS
.browsers-to-be-fixed div {
    content: "images/stack.svg#icon-1";
    width: 50px;
    height: 50px;
    background: no-repeat;
    background-size: 100% 100%;
    }
```

Instead, we have to redundantly add the value of background image in order to make it work:

``` CSS
.browsers-to-be-fixed div {
    content: "images/stack.svg#icon-1";
    width: 50px;
    height: 50px;
    background: url(images/stack.svg#icon-1) no-repeat;
    background-size: 100% 100%;
    }
```

The point is that, when we are writing code only for browsers which need to be fixed, we should be able to omit the value of background image because those browsers don't support the value anyway.
